# Input/output configuration
input_dir: ${EMBEDDING_OUTPUT}
output_dir: ${FILTER_OUTPUT}
project: ${PROJECT_NAME}-filtering
filter_cut: 0.01 #0.04 #0.15
overwrite: True

# Dataset parameters
pt_background_min: 0.
pt_signal_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[950,25,25]] # Number of [training, validation, testing] examples
noise: False
true_edges: modulewise_true_edges


# Model parameters
n_chunks: 12
in_channels: 3
hidden: 1024 #512
nb_layer: 8
emb_channels: 0
layernorm: True
batchnorm: False
edges_per_batch: 300000
ratio: 2
weight: 1
val_subset: 0.1
warmup: 800 #400
lr: 0.001
factor: 0.4 #0.3
patience: 9 #8
regime: [[]] #[[weighting, ci]]
max_epochs: 20 #25 #100

# Post-processing
callbacks: [[FilteringModelCheckpoint, GraphSizeMonitor, FilterTelemetry, FilterBuilder]]

