# Input/output configuration
input_dir: ${PROCESSING_OUTPUT}
output_dir: ${EMBEDDING_OUTPUT}
project: ${PROJECT_NAME}-embedding
overwrite: True

# Dataset parameters
pt_signal_cut: 0.0
pt_background_cut: 0.0
train_split: [[950,25,25]] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 0
emb_hidden: 1024 #1024
nb_layer: 4 # 4
emb_dim: 12
weight: 2
activation: Tanh
randomisation: 4 #2
points_per_batch: 130000
r_train: 0.2 # 0.1
r_val: 0.2 # 0.1
r_test: 0.2 # 0.1
knn: 50 #100
warmup: 4 #3
margin: 0.2 #0.1
lr: 0.0003 #0.0001
factor: 0.58 #0.3
patience: 19 #10
regime: [[rp, hnm, norm]] #ci
max_epochs: 20 #50 #100

# Postprocessing
callbacks: [[EmbeddingModelCheckpoint, EmbeddingTelemetry, EmbeddingBuilder]]
