stage_list:
    - {set: Processing, name: TrackMLFeatureStore, config: processing.yaml}
    - {set: Embedding, name: LayerlessEmbedding, config: embedding.yaml}
    - {set: Filter, name: VanillaFilter, config: filter.yaml}
    - {set: GNN, name: InteractionGNN, config: gnn.yaml}
#    - {set: Segmenting, name: TrackMLSegment, config: segment_config_1k_events_ODD_no_cut.yaml}
